// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: anime/anime-search.proto

package anime

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_anime_anime_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anime_anime_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_anime_anime_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type GetByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIdRequest) Reset() {
	*x = GetByIdRequest{}
	mi := &file_anime_anime_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIdRequest) ProtoMessage() {}

func (x *GetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anime_anime_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIdRequest.ProtoReflect.Descriptor instead.
func (*GetByIdRequest) Descriptor() ([]byte, []int) {
	return file_anime_anime_search_proto_rawDescGZIP(), []int{1}
}

func (x *GetByIdRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_anime_anime_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anime_anime_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_anime_anime_search_proto_rawDescGZIP(), []int{2}
}

type AnimeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Synopsis      string                 `protobuf:"bytes,3,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeItem) Reset() {
	*x = AnimeItem{}
	mi := &file_anime_anime_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeItem) ProtoMessage() {}

func (x *AnimeItem) ProtoReflect() protoreflect.Message {
	mi := &file_anime_anime_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeItem.ProtoReflect.Descriptor instead.
func (*AnimeItem) Descriptor() ([]byte, []int) {
	return file_anime_anime_search_proto_rawDescGZIP(), []int{3}
}

func (x *AnimeItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnimeItem) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AnimeItem) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*AnimeItem           `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_anime_anime_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anime_anime_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_anime_anime_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetResults() []*AnimeItem {
	if x != nil {
		return x.Results
	}
	return nil
}

type AnimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Anime         *AnimeItem             `protobuf:"bytes,1,opt,name=anime,proto3" json:"anime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimeResponse) Reset() {
	*x = AnimeResponse{}
	mi := &file_anime_anime_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeResponse) ProtoMessage() {}

func (x *AnimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anime_anime_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeResponse.ProtoReflect.Descriptor instead.
func (*AnimeResponse) Descriptor() ([]byte, []int) {
	return file_anime_anime_search_proto_rawDescGZIP(), []int{5}
}

func (x *AnimeResponse) GetAnime() *AnimeItem {
	if x != nil {
		return x.Anime
	}
	return nil
}

var File_anime_anime_search_proto protoreflect.FileDescriptor

const file_anime_anime_search_proto_rawDesc = "" +
	"\n" +
	"\x18anime/anime-search.proto\x12\x05anime\"%\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\" \n" +
	"\x0eGetByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\r\n" +
	"\vListRequest\"M\n" +
	"\tAnimeItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bsynopsis\x18\x03 \x01(\tR\bsynopsis\"<\n" +
	"\x0eSearchResponse\x12*\n" +
	"\aresults\x18\x01 \x03(\v2\x10.anime.AnimeItemR\aresults\"7\n" +
	"\rAnimeResponse\x12&\n" +
	"\x05anime\x18\x01 \x01(\v2\x10.anime.AnimeItemR\x05anime2\xbf\x01\n" +
	"\fAnimeService\x12:\n" +
	"\vSearchAnime\x12\x14.anime.SearchRequest\x1a\x15.anime.SearchResponse\x12;\n" +
	"\fGetAnimeById\x12\x15.anime.GetByIdRequest\x1a\x14.anime.AnimeResponse\x126\n" +
	"\tListAnime\x12\x12.anime.ListRequest\x1a\x15.anime.SearchResponseB0Z.github.com/merdernoty/anime-search/proto;animeb\x06proto3"

var (
	file_anime_anime_search_proto_rawDescOnce sync.Once
	file_anime_anime_search_proto_rawDescData []byte
)

func file_anime_anime_search_proto_rawDescGZIP() []byte {
	file_anime_anime_search_proto_rawDescOnce.Do(func() {
		file_anime_anime_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anime_anime_search_proto_rawDesc), len(file_anime_anime_search_proto_rawDesc)))
	})
	return file_anime_anime_search_proto_rawDescData
}

var file_anime_anime_search_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_anime_anime_search_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: anime.SearchRequest
	(*GetByIdRequest)(nil), // 1: anime.GetByIdRequest
	(*ListRequest)(nil),    // 2: anime.ListRequest
	(*AnimeItem)(nil),      // 3: anime.AnimeItem
	(*SearchResponse)(nil), // 4: anime.SearchResponse
	(*AnimeResponse)(nil),  // 5: anime.AnimeResponse
}
var file_anime_anime_search_proto_depIdxs = []int32{
	3, // 0: anime.SearchResponse.results:type_name -> anime.AnimeItem
	3, // 1: anime.AnimeResponse.anime:type_name -> anime.AnimeItem
	0, // 2: anime.AnimeService.SearchAnime:input_type -> anime.SearchRequest
	1, // 3: anime.AnimeService.GetAnimeById:input_type -> anime.GetByIdRequest
	2, // 4: anime.AnimeService.ListAnime:input_type -> anime.ListRequest
	4, // 5: anime.AnimeService.SearchAnime:output_type -> anime.SearchResponse
	5, // 6: anime.AnimeService.GetAnimeById:output_type -> anime.AnimeResponse
	4, // 7: anime.AnimeService.ListAnime:output_type -> anime.SearchResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_anime_anime_search_proto_init() }
func file_anime_anime_search_proto_init() {
	if File_anime_anime_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anime_anime_search_proto_rawDesc), len(file_anime_anime_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anime_anime_search_proto_goTypes,
		DependencyIndexes: file_anime_anime_search_proto_depIdxs,
		MessageInfos:      file_anime_anime_search_proto_msgTypes,
	}.Build()
	File_anime_anime_search_proto = out.File
	file_anime_anime_search_proto_goTypes = nil
	file_anime_anime_search_proto_depIdxs = nil
}
